In [1]:
import tensorflow as tf

In [2]:
from tensorflow.keras.layers import Input, Dense
from tensorflow.keras import Model

import numpy as np

In [3]:
# Wie definieren ein Modell: 
# 1. Den Input (eine natürliche Zahl)

In [4]:
input_layer = Input(shape=(1,), name="Input_Layer")

In [5]:
print(input_layer)

Tensor("Input_Layer:0", shape=(None, 1), dtype=float32)


In [6]:
input_for_training = [2,3,4,5,6,7]
results_1 = np.array(input_for_training) * 3
results_2 = [2] + np.array(input_for_training)
print (results_1, results_2)

# results_total = tf.concat([[results_1], [results_2]],0)

results_total = [[6,4],[9,5],[12,6],[15,7], [18,8], [21,9]]
print (results_total)

[ 6  9 12 15 18 21] [4 5 6 7 8 9]
[[6, 4], [9, 5], [12, 6], [15, 7], [18, 8], [21, 9]]


In [7]:
shared_layer = Dense(2, name="shared_layer")(input_layer)
out_layer_1 = Dense(1, name ="out_1")(shared_layer)
out_layer_2 = Dense(1, name="out_2")(shared_layer)
total_out = tf.concat([out_layer_1, out_layer_2],1, name="concat_output")

model = Model(inputs=input_layer, outputs=total_out)

model.summary()



Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 1)]          0                                            
__________________________________________________________________________________________________
shared_layer (Dense)            (None, 2)            4           Input_Layer[0][0]                
__________________________________________________________________________________________________
out_1 (Dense)                   (None, 1)            3           shared_layer[0][0]               
__________________________________________________________________________________________________
out_2 (Dense)                   (None, 1)            3           shared_layer[0][0]               
______________________________________________________________________________________________

In [8]:
model.compile(optimizer="SGD", loss='mae')

print(model.predict([1]))


[[-0.36182025  0.36417103]]


In [9]:
model.fit(input_for_training, results_total, epochs=50)

Train on 6 samples
Epoch 1/50
6/6 [==============================] - 1s 103ms/sample - loss: 9.9947
Epoch 2/50
6/6 [==============================] - 0s 2ms/sample - loss: 9.9542
Epoch 3/50
6/6 [==============================] - 0s 3ms/sample - loss: 9.9136
Epoch 4/50
6/6 [==============================] - 0s 4ms/sample - loss: 9.8727
Epoch 5/50
6/6 [==============================] - 0s 4ms/sample - loss: 9.8314
Epoch 6/50
6/6 [==============================] - 0s 3ms/sample - loss: 9.7896
Epoch 7/50
6/6 [==============================] - 0s 3ms/sample - loss: 9.7470
Epoch 8/50
6/6 [==============================] - 0s 4ms/sample - loss: 9.7036
Epoch 9/50
6/6 [==============================] - 0s 3ms/sample - loss: 9.6592
Epoch 10/50
6/6 [==============================] - 0s 4ms/sample - loss: 9.6136
Epoch 11/50
6/6 [==============================] - 0s 5ms/sample - loss: 9.5666
Epoch 12/50
6/6 [==============================] - 0s 3ms/sample - loss: 9.5180
Epoch 13/50
6/6 [===========

In [10]:
model.predict([10])


array([[ 3.7505715, 13.654433 ]], dtype=float32)

In [11]:
for l in model.layers:
    print (l.name)

Input_Layer
shared_layer
out_1
out_2
tf_op_layer_concat_output


In [12]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 1)]          0                                            
__________________________________________________________________________________________________
shared_layer (Dense)            (None, 2)            4           Input_Layer[0][0]                
__________________________________________________________________________________________________
out_1 (Dense)                   (None, 1)            3           shared_layer[0][0]               
__________________________________________________________________________________________________
out_2 (Dense)                   (None, 1)            3           shared_layer[0][0]               
______________________________________________________________________________________________

In [13]:
for l in model.layers:
    if (l.name == "shared_layer"):
        # print(dir(l))
        l.trainable = False

In [14]:

model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
Input_Layer (InputLayer)        [(None, 1)]          0                                            
__________________________________________________________________________________________________
shared_layer (Dense)            (None, 2)            4           Input_Layer[0][0]                
__________________________________________________________________________________________________
out_1 (Dense)                   (None, 1)            3           shared_layer[0][0]               
__________________________________________________________________________________________________
out_2 (Dense)                   (None, 1)            3           shared_layer[0][0]               
______________________________________________________________________________________________

In [15]:
model_2 = Model(inputs=input_layer, outputs=[shared_layer])
model_2.compile(optimizer="SGD", loss="mae")
print (model_2.predict([2, 3, 4, 5]))
model.predict([2,3,4,5])

[[-0.49948293  2.2459445 ]
 [-0.7362324   3.3035643 ]
 [-0.9729818   4.361184  ]
 [-1.2097312   5.418804  ]]


array([[0.98363566, 3.0262718 ],
       [1.3295026 , 4.354792  ],
       [1.6753696 , 5.6833124 ],
       [2.0212367 , 7.0118327 ]], dtype=float32)

In [16]:
model.get_layer("shared_layer").get_weights()

[array([[-0.23674943,  1.0576198 ]], dtype=float32),
 array([-0.02598408,  0.13070491], dtype=float32)]

In [17]:
model_2.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (InputLayer)     [(None, 1)]               0         
_________________________________________________________________
shared_layer (Dense)         (None, 2)                 4         
Total params: 4
Trainable params: 0
Non-trainable params: 4
_________________________________________________________________


In [18]:
new_out_layer = Dense(5)(shared_layer)

model_3 = Model(inputs=input_layer, outputs=[new_out_layer])

model_3.summary()


Model: "model_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
Input_Layer (InputLayer)     [(None, 1)]               0         
_________________________________________________________________
shared_layer (Dense)         (None, 2)                 4         
_________________________________________________________________
dense (Dense)                (None, 5)                 15        
Total params: 19
Trainable params: 15
Non-trainable params: 4
_________________________________________________________________
